TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
#DB += circle.db
DB += rpiControl.db
#DB += rpiSensors-simul.db
DB += raspiVentVersion.db

DB += rpiSensors-simul-arduino.db
#DB += rpiSensors-arduino.db
DB += rpiControl-arduino.db
DB += arduino.proto
#DB += dbSubExample.db
#DB += user.substitutions
#DB += dbExample1.db
#DB += dbExample2.db

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

